// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantListingAPI.Data;

#nullable disable

namespace RestaurantListingAPI.Migrations
{
    [DbContext(typeof(RestaurantListingDbContext))]
    partial class RestaurantListingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantListingAPI.Data.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Bosnia and Herzegowina",
                            Name = "Orasje"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Croatia",
                            Name = "Osijek"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Croatia",
                            Name = "Zagreb"
                        });
                });

            modelBuilder.Entity("RestaurantListingAPI.Data.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "4. ulica",
                            CityId = 1,
                            Name = "Baca",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 2,
                            Address = "75. ulica",
                            CityId = 2,
                            Name = "Hamburgila",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ilica 45",
                            CityId = 3,
                            Name = "Pivana Zuja",
                            Rating = 4.9000000000000004
                        });
                });

            modelBuilder.Entity("RestaurantListingAPI.Data.Restaurant", b =>
                {
                    b.HasOne("RestaurantListingAPI.Data.City", "City")
                        .WithMany("Restaurants")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("RestaurantListingAPI.Data.City", b =>
                {
                    b.Navigation("Restaurants");
                });
#pragma warning restore 612, 618
        }
    }
}
